name: mobile_ai_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  path_provider: ^2.0.15
  provider: ^6.1.1
  path: ^1.8.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/d.png"

flutter:
  uses-material-design: true
